sudo: required
services:
  - docker

before_install:
  - docker build -t thanhdat27/react-test -f ./client/Dockerfile.dev ./client
scrpit:
  - docker run -e CI=true thanhdat27/react-test npm test
after_success:
  - docker build -t thanhdat27/multi-client ./client
  - docker build -t thanhdat27/multi-nginx ./nginx
  - docker build -t thanhdat27/multi-server ./server
  - docker build -t thanhdat27/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push thanhdat27/multi-client
  - docker push thanhdat27/multi-nginx
  - docker push thanhdat27/multi-server
  - docker push thanhdat27/multi-worker
deploy:
  edge: true
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-312538530133'
  bucket_path: 'multi-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
